// Code generated by scripts/contract-codegen.mjs from contract/openapi.yaml.
// DO NOT EDIT — run `pnpm contract:codegen` instead.

/**
 * The recipe-service HTTP contract, as TypeScript.
 *
 * Re-exported by `@pantry/types`; import from there, not from this file.
 */

/** The liveness payload. Always `{"status":"ok"}`. */
export interface HealthResponse {
  status: string;
}

/**
 * Every non-2xx response body. One field, always present: the message
 * `writeError` recorded, never a stack or an internal cause.
 */
export interface ErrorResponse {
  error: string;
}

/** How many recipes the account-deletion cascade removed (BL-0068). */
export interface DeleteUserRecipesResponse {
  deleted: number;
}

export interface Ingredient {
  quantity: number;
  unit: string;
  item: string;
  note?: string;
}

/**
 * The closed cooking-method enum (BL-0041). Closed on purpose: BL-0042's
 * prep rules key on these values, and rules cannot be written against a
 * vocabulary that varies per recipe. recipe-service is the source of truth
 * (`internal/recipe/equipment.json`).
 *
 * Deliberately a type and not a runtime array on the TypeScript side.
 * `@pantry/types` ships as `dist` only, and nothing else in the repo
 * imports a VALUE from it: the Convex bundler and the Vite dev server both
 * resolve it without a build step only while every import is
 * `import type`. Consumers that need the members at runtime declare their
 * own list and prove it covers this union at compile time — see
 * packages/convex/convex/recipes.ts and apps/web/src/lib/cookingMethods.ts.
 */
export type CookingMethod =
  | "bake"
  | "roast"
  | "grill"
  | "smoke"
  | "sous_vide"
  | "slow_cook"
  | "pressure_cook"
  | "fry"
  | "saute"
  | "boil"
  | "marinate"
  | "no_cook";

export type EquipmentCategory = "appliance" | "cookware" | "tool";

/** One entry of the curated hardware catalog served by GET /equipment. */
export interface EquipmentDef {
  id: string;
  name: string;
  category: EquipmentCategory;
  aliases: string[];
  /**
   * Methods that follow unambiguously from the equipment ("crock pot"
   * means slow_cook). Absent where the mapping is not certain — a stand
   * mixer says nothing about how the dish is cooked.
   */
  implies?: CookingMethod[];
}

/**
 * An equipment tag on a recipe, referencing the catalog by slug.
 * `required: false` is "a grill pan works too" — optional gear must not
 * block BL-0043's "can I make this?" check.
 */
export interface RecipeEquipment {
  id: string;
  required: boolean;
}

/**
 * When, relative to the cook date, a piece of prep has to happen (BL-0042).
 *
 * Coarse by design — day granularity, no clock times — because the planner
 * schedules meals onto days and nothing in it knows what time dinner is.
 * Ordered coarsest lead time first, which is also the order tasks are shown
 * in: the three-day thaw is both the most urgent to see and the easiest to
 * miss.
 */
export type PrepWindow =
  | "three_days_before"
  | "two_days_before"
  | "night_before"
  | "morning_of"
  | "hour_before"
  | "at_start";

/**
 * Which producer emitted a task (BL-0044).
 *
 * Three producers, one stream, one precedence order: `manual > llm > rule`,
 * applied per task key. A hand-authored task therefore *replaces* the rule
 * task it shares a key with rather than appearing beside it.
 *
 * - `rule` — derived on read from the versioned rule table. Never stored,
 *   so improving a rule improves every recipe at once.
 * - `llm` — the model matched a rule the deterministic scan missed. The
 *   text is still the rule's; the model chose the match, not the words.
 * - `manual` — the user wrote it.
 */
export type PrepSource = "rule" | "llm" | "manual";

/**
 * A prep task stored on a recipe: the two producers whose output cannot be
 * recomputed. Carries no rule id and no due date — it is not derived, and
 * its due date depends on the meal it is scheduled for.
 */
export interface StoredPrepTask {
  /**
   * The merge identity, shared with `PrepTask.key`.
   *
   * A task written to *override* a derived one carries that task's key
   * verbatim; that is how "this rule is wrong for this recipe" is
   * expressed. A task written fresh gets a key from its own text
   * (`manual:take-the-turkey-out`), assigned by the server.
   */
  key: string;
  window: PrepWindow;
  text: string;
  source: PrepSource;
}

/**
 * A prep task on its way *to* the server.
 *
 * `key` is omitted when authoring something new and echoed back verbatim
 * when editing or overriding. `source` is omitted entirely: the server
 * stamps the producer it is writing for, so a client cannot label its own
 * guess as something the user wrote. (Create accepts an explicit `llm` for
 * tasks a fresh import produced, since the import preview is never
 * persisted server-side.)
 */
export interface PrepTaskInput {
  key?: string;
  window: PrepWindow;
  text: string;
  /** Never `rule` — rule-derived prep is computed, never stored. */
  source?: "llm" | "manual";
}

export interface Recipe {
  id: string;
  userId: string;
  title: string;
  /**
   * How many people the recipe feeds. Absent means the yield is unknown —
   * existing recipes and manual entry without a yield both leave it
   * unset, so consumers must omit per-serving figures rather than assume
   * a default.
   *
   * This is an absolute count. It is not the planner's
   * `servingsMultiplier`, which is a scale factor ("cook 1.5x this
   * recipe") on a basket entry.
   */
  servings?: number;
  ingredients: Ingredient[];
  /** Ordered instruction lines (the method). Empty for ingredients-only recipes. */
  steps: string[];
  /** Equipment tags referencing the catalog. Empty when nothing was detected. */
  equipment: RecipeEquipment[];
  /** Members of the closed method enum. Empty when nothing was detected. */
  methods: CookingMethod[];
  /**
   * Discovery metadata (BL-0020) — what the catalog's filter chips read.
   *
   * `cuisine` and `tags` are an OPEN vocabulary, deliberately unlike
   * `methods`. Methods are closed because BL-0042's prep rules key on
   * them; nothing keys on a cuisine or a tag, so an import that meets a
   * cuisine we have never heard of should keep it rather than drop it.
   * recipe-service normalizes both to slugs, so "Gluten Free" and
   * "gluten_free" are one chip.
   *
   * Absent when unknown.
   */
  cuisine?: string;
  /**
   * Wall-clock minutes from starting to eating. Absent means unknown —
   * never zero, and never sorted or filtered as if it were fast. This is
   * the #1 weeknight filter.
   */
  totalMinutes?: number;
  /**
   * Free-form slugs ("vegan", "one-pot"). Diet lives here rather than in
   * its own field: the UI groups the tags it recognizes as diets into a
   * chip row, and a tag it does not recognize stays searchable instead of
   * being dropped.
   */
  tags: string[];
  /** Where the recipe came from, for attribution and re-import. Absent when hand-entered. */
  sourceUrl?: string;
  /**
   * The catalog recipe this one was cloned from (BL-0020's clone-on-add).
   *
   * Server-owned and read-only: it is the idempotency key that stops a
   * second "Add to basket" from making a second copy, so a client cannot
   * set it. Present only on recipes that came from the catalog.
   */
  sourceRecipeId?: string;
  /**
   * Prep tasks stored on the recipe: hand-authored and model-derived
   * (BL-0044). Rule-derived prep is absent here — it is computed on read
   * from the rule table and merged with these, precedence
   * `manual > llm > rule`. Usually empty.
   */
  prepTasks: StoredPrepTask[];
  createdAt: string;
}

/**
 * The write shape for a recipe. Update accepts exactly the same fields and
 * replaces the recipe wholesale, so an omitted field CLEARS the stored
 * value — callers echo back whatever they want to keep. `sourceRecipeId` is
 * absent by design: it is server-owned provenance, not something a client
 * sets.
 */
export interface CreateRecipeRequest {
  title: string;
  /** Omit when unknown; recipe-service rejects a value outside 1..100. */
  servings?: number;
  ingredients: Ingredient[];
  steps?: string[];
  equipment?: RecipeEquipment[];
  methods?: CookingMethod[];
  /** Free text; recipe-service slugifies it. Omit when unknown. */
  cuisine?: string;
  /** Omit when unknown. recipe-service rejects zero and negatives. */
  totalMinutes?: number;
  tags?: string[];
  /** Must be an absolute http(s) URL; anything else is rejected. */
  sourceUrl?: string;
  /**
   * Unlike every field above, an ABSENT value does not clear the stored
   * rows: two producers write them independently, so a client that knows
   * nothing about prep must not be able to delete what the model tagged
   * at import. Send `[]` to clear.
   */
  prepTasks?: PrepTaskInput[];
}

export interface ImportRecipeRequest {
  url: string;
}

/**
 * One recipe on a plan, at the servings dial it is planned at. The same shape feeds POST
 * /grocery-list and POST /nutrition/estimate.
 */
export interface GroceryListItem {
  recipeId: string;
  multiplier: number;
}

export interface GroceryListRequest {
  items: GroceryListItem[];
}

/**
 * One recipe's contribution to an aggregated grocery line.
 *
 * `quantity` is in the *parent line's* unit, not the unit the recipe wrote,
 * so the contributions add up to the line total — that additivity is the
 * question the provenance sheet answers ("why is this ¾ cup?"). The unit is
 * therefore not repeated here.
 */
export interface GroceryLineSource {
  recipeId: string;
  title: string;
  quantity: number;
}

/**
 * What to actually buy for a line, and what survives the cooking (BL-0032).
 *
 * This rides ALONGSIDE the line's quantity rather than replacing it: the
 * quantity is the need the recipes add up to, and provenance, don't-rebuy
 * and pricing are all built on that number. The purchase is a second claim
 * — buy this, need that — because nobody sells 2 tbsp of parsley.
 */
export interface GroceryPurchase {
  /** Whole packs: you cannot buy four fifths of a bunch. */
  quantity: number;
  /** The pack's own name ("bunch", "can"), singular — clients pluralize. */
  unit: string;
  /** Surplus left once the recipes take their share; absent on an exact fit. */
  residue?: number;
  residueUnit?: string;
}

export interface GroceryLine {
  item: string;
  /** Normalized ingredient key ("green onion"); the identity the pantry joins on. */
  canonicalItem: string;
  unit: string;
  quantity: number;
  aisle: string;
  /**
   * The recipes this line was aggregated from, in first-seen order.
   * Absent for manually added lines and for lines generated before
   * BL-0019.
   */
  sources?: GroceryLineSource[];
  /**
   * How this item is sold, when the normalization dataset knows. Absent
   * for most of the list — see `GroceryPurchase`.
   */
  purchase?: GroceryPurchase;
}

/**
 * Whether a recipe's hardware requirements are met by an equipment
 * inventory (BL-0043).
 *
 * `unknown` is the important one: a recipe carrying no equipment tags has
 * never been assessed, and presenting that as `makeable` would turn missing
 * data into a green light. UI must render it as "we don't know", never as a
 * yes.
 */
export type EquipmentFitStatus = "makeable" | "blocked" | "unknown";

/**
 * How one recipe fares against an inventory, without the recipe body — the
 * compact shape the catalog joins onto recipes it already has.
 */
export interface EquipmentFit {
  status: EquipmentFitStatus;
  /** Required equipment slugs the user lacks. Empty unless status is "blocked". */
  missing: string[];
  /** Which newly acquired devices this recipe needed. Only set by a discovery query. */
  unlockedBy: string[];
}

/** A recipe plus its fit — the shape POST /equipment/match returns. */
export type EquipmentMatch = Recipe & EquipmentFit;

/**
 * Bucket sizes over every recipe considered — including recipes the
 * narrowed list omits, so "N we can't assess" keeps an honest denominator.
 */
export interface EquipmentCounts {
  makeable: number;
  blocked: number;
  unknown: number;
}

export interface EquipmentMatchResult {
  recipes: EquipmentMatch[];
  counts: EquipmentCounts;
}

export interface EquipmentMatchRequest {
  /** Every equipment slug the user has. */
  owned: string[];
  /**
   * Turns this into the new-device query. Its members must also appear in
   * `owned` — you cannot be unlocked by hardware you don't have.
   */
  acquired?: string[];
}

/** An item's typical pack, as the dataset knows it — "bunch", 0.5 cup. */
export interface PurchasePack {
  unit: string;
  size: number;
  sizeUnit: string;
}

/**
 * Everything the normalizer knows about one ingredient — the wire shape of
 * POST /normalization/lookup, which is how Convex reads shelf life without
 * keeping a second copy of the table.
 */
export interface ItemDetails {
  canonicalItem: string;
  display: string;
  aisle: string;
  /**
   * Absent rather than zero when unknown, so callers can tell "we don't know" from "it expires
   * today".
   */
  shelfLifeDays?: number;
  /** The what-is-it axis prep rules match on; absent when unclassified. */
  category?: string;
  /**
   * A keep-on-hand ingredient. Absent (false) for every unknown item: we do not assume
   * something we failed to recognize is one.
   */
  staple?: boolean;
  /**
   * The allergen families this item belongs to, sorted, or absent for an
   * item in none — and for every unknown item, since an ingredient we do
   * not recognize is one whose allergens we cannot claim to know.
   *
   * A LIST because families overlap: egg noodles are both egg and wheat.
   */
  allergens?: string[];
  /**
   * The typical purchase size, when the dataset knows one. Absent means "sold however the
   * recipe measures it, as far as we know".
   */
  purchase?: PurchasePack;
  /**
   * Whether the dataset actually recognized the item. Unknown items still
   * get a `canonicalItem` — the normalized raw text — so callers can group
   * by it, but nothing else about them is asserted. Callers that need to
   * tell "we know this is bread" from "we have never seen this word" must
   * read this rather than inferring it from an "other" aisle.
   */
  known: boolean;
}

export interface NormalizationLookupRequest {
  /** Raw ingredient text; canonicalization happens server-side. */
  items: string[];
}

export interface NormalizationLookupResponse {
  items: ItemDetails[];
}

/**
 * What one avoid-list entry turned out to be (BL-0052).
 *
 * - `item` — one canonical ingredient.
 * - `allergen` — a whole family, which excludes every one of its `members`.
 * - `unknown` — the dictionary has never seen this text, so the entry will
 *   remove no recipe. That case is the reason this type exists: an avoid
 *   entry that silently matches nothing is the bug, and for a declared
 *   allergy it is not a cosmetic one.
 */
export type AvoidResolutionKind = "item" | "allergen" | "unknown";

/** The wire shape of POST /normalization/avoid, one entry in, one out. */
export interface AvoidResolution {
  /** The text the user actually typed, so a client can say "scallion → green onion". */
  input: string;
  /** What gets STORED: a canonical item key, a family key, or the normalized text. */
  canonicalItem: string;
  display: string;
  kind: AvoidResolutionKind;
  /** Display names of everything an allergen family excludes. `allergen` only. */
  members?: string[];
  /** Families a single item belongs to — a nudge toward the broader entry. `item` only. */
  families?: string[];
}

export interface AvoidResolutionRequest {
  entries: string[];
}

export interface AvoidResolutionResponse {
  entries: AvoidResolution[];
}

/**
 * One piece of ingredient text the dictionary did not recognize, with how often it appeared and
 * where.
 */
export interface UnresolvedIngredient {
  /** The text as the normalizer saw it, lowercased and trimmed. */
  item: string;
  count: number;
  /** Recipe titles the text appeared in, so an operator can go look at the line. */
  examples: string[];
}

/** The dictionary's report card over some body of ingredient text. */
export interface CoverageReport {
  lines: number;
  resolved: number;
  /** resolved/lines in [0,1], and 0 for an empty corpus — nothing measured is not full marks. */
  share: number;
  /**
   * Ordered by count descending, then item ascending, so the most valuable dictionary entry to
   * write next is always first.
   */
  unresolved: UnresolvedIngredient[];
}

/**
 * One nutrient amount, keyed by FDC nutrient number ("1008" energy kcal,
 * "1003" protein, "1253" cholesterol). We use FDC's numbering rather than
 * inventing a parallel taxonomy.
 */
export interface NutrientAmount {
  nutrientId: string;
  amount: number;
  unit: string;
}

/** How much of a recipe the estimate actually accounts for. Never optional. */
export interface NutritionCoverage {
  /** 0..1 of the recipe's mass that resolved to a food with nutrient data. */
  resolvedMassFraction: number;
  resolvedCount: number;
  totalCount: number;
}

/** Per-ingredient provenance: what we made of each line, and why we failed. */
export interface NutritionIngredient {
  item: string;
  /** null when the line's mass could not be determined. */
  grams: number | null;
  /** True only if the line contributed nutrients — mass known AND food matched. */
  resolved: boolean;
  /** Why the line is unresolved, e.g. `no gram weight for unit "pinch"`. */
  reason?: string;
  /** How the grams were derived: mass | portion | density | count. */
  method?: string;
  /** The FDC description matched, so a wrong fuzzy match is visible. */
  matchedFood?: string;
}

/**
 * One recipe's contribution to a multi-recipe rollup (BL-0037).
 *
 * A single blended `resolvedMassFraction` cannot express every way a rollup
 * is incomplete: it describes the food it *saw*. A recipe that could not be
 * loaded at all contributes to neither side of that ratio, so a day missing
 * a whole dinner would otherwise read as fully covered. `counted` is that
 * case, named.
 */
export interface NutritionRecipeCoverage {
  recipeId: string;
  /** Absent when the recipe could not be read — an unreadable recipe leaks nothing. */
  title?: string;
  /** The servings dial this recipe contributed at. */
  multiplier: number;
  /** False when the recipe's ingredients never reached the totals at all. */
  counted: boolean;
  /** This recipe's own coverage, so the one bad dish can be named. */
  coverage: NutritionCoverage;
}

/**
 * An estimated nutrient vector for a recipe or a selection of recipes.
 *
 * `nutrients` is an open map on purpose — adding a nutrient must be a data
 * change, never a wire-type change across three languages. Do not narrow it
 * to a typed macro struct.
 */
export interface NutritionEstimate {
  nutrients: Record<string, NutrientAmount>;
  /** Absent when the recipe's yield is unknown; never divided by a guess. */
  perServing?: Record<string, NutrientAmount>;
  servings: number;
  coverage: NutritionCoverage;
  ingredients: NutritionIngredient[];
  estimatedAt: string;
  /**
   * Present only on a rollup (POST /nutrition/estimate), where "which dish is missing?" is a
   * question the blended coverage figure cannot answer.
   */
  recipes?: NutritionRecipeCoverage[];
}

export interface NutritionEstimateRequest {
  items: GroceryListItem[];
}

/** How stale the underlying price table is, graded when the estimate is made. */
export type PriceStaleness = "fresh" | "aging" | "stale";

/** Provenance for an estimate. A total shown without this is a number pretending to be a price. */
export interface PriceBasis {
  source: string;
  sourceUrl: string;
  /** Geographic basis of the averages, e.g. "U.S. city average". */
  area: string;
  /** "YYYY-MM" the prices were observed. */
  observationMonth: string;
  staleness: PriceStaleness;
  store?: StorePriceBasis;
}

/** Per-line outcome. Unpriced lines carry a reason and contribute nothing to the total. */
export interface PricedLine {
  canonicalItem: string;
  item: string;
  priced: boolean;
  cents?: number;
  /** Which coarse price bucket the ingredient resolved to. */
  bucket?: string;
  bucketLabel?: string;
  /** Why the line could not be priced, when `priced` is false. */
  reason?: string;
  source?: PriceSource;
  /**
   * The shelf item a store price came from, so a number can be shown as the price of something
   * specific. Absent for an average.
   */
  product?: string;
  /**
   * True when the store price is a promotion rather than the regular shelf price, and so will
   * not last.
   */
  onSale?: boolean;
}

/**
 * Grocery pricing (BL-0023 increment 1).
 *
 * Deliberately a separate contract from GroceryLine rather than fields on
 * it: price data has its own source, refresh cadence and legal constraints,
 * and the grocery list must keep working when pricing is unavailable.
 */
export interface CostEstimate {
  currency: string;
  totalCents: number;
  pricedCount: number;
  unpricedCount: number;
  lines: PricedLine[];
  basis: PriceBasis;
}

/** One aggregated grocery line to price: the normalized identity plus its quantity. */
export interface PricingLine {
  canonicalItem: string;
  item: string;
  unit: string;
  quantity: number;
}

export interface PricingEstimateRequest {
  lines: PricingLine[];
  /**
   * The store the user opted into (BL-0046). Absent — which is every user who has not chosen
   * one — prices the list from the national averages alone.
   */
  storeLocationId?: string;
}

/** Which table priced a line. Absent on an unpriced line, where there is no number to attribute. */
export type PriceSource = "average" | "store";

/**
 * Provenance for the store-priced half of an estimate (BL-0046).
 *
 * It sits alongside the averages basis rather than replacing it, because a
 * mixed estimate genuinely has two sources, and is present only when the
 * chosen store actually priced something.
 */
export interface StorePriceBasis {
  provider: string;
  locationId: string;
  storeName?: string;
  /** RFC 3339. Shelf prices move daily, so the age of the quote is part of the number. */
  fetchedAt: string;
  /**
   * How many lines the store priced. The rest came from the averages, and saying so is what
   * keeps a mixed total honest.
   */
  pricedCount: number;
}

/** One store a user can choose to price against. */
export interface StoreLocation {
  locationId: string;
  name: string;
  chain?: string;
  address?: string;
  city?: string;
  state?: string;
  zipCode?: string;
}

export interface StoreSearchRequest {
  zipCode: string;
  /** Defaults to 10 and is capped at 100 by the provider. */
  radiusMiles?: number;
}

/**
 * Nearby stores. An empty provider means real store prices are not configured, which a client
 * renders by offering no chooser at all.
 */
export interface StoreSearchResult {
  provider: string;
  stores: StoreLocation[];
}

/**
 * Whether real store prices are configured on this deployment. This is the BL-0046 feature flag
 * as seen from outside the service.
 */
export interface StoreProviderStatus {
  enabled: boolean;
  provider: string;
}

/** One pantry row as the recommender sees it. */
export interface PantryContextItem {
  canonicalItem: string;
  state: "have" | "low" | "out";
  useItUp?: boolean;
  /**
   * Approximate spoil date, epoch ms (BL-0029). Absent when the
   * shelf-life table doesn't recognize the item — which is not the same
   * as "keeps forever", and is why the ranker treats absence as no signal
   * rather than as a far-off date.
   */
  useBy?: number;
}

/** Ingredient-grounded preferences. `avoidItems` is a hard filter, not a weight. */
export interface RecommendationPreferences {
  avoidItems: string[];
  likedItems: string[];
  dislikedItems: string[];
  /**
   * Cuisine slugs the cook says they like (BL-0030), from the same open
   * vocabulary a recipe's single `cuisine` is stored in.
   *
   * A SET here against one value on the recipe: a cook likes several
   * cuisines, a dish is one of them. Omitted or empty means no stated
   * taste, which makes the ranker's `cuisineMatch` unavailable rather
   * than making every recipe a miss.
   */
  cuisines?: string[];
  /**
   * The cook time the user is willing to spend, in minutes, or omitted
   * for no opinion.
   *
   * A recipe whose `totalMinutes` is unknown is scored against this as
   * UNMEASURED, never as fast — an untimed recipe winning "I have 20
   * minutes" is the failure this field is most likely to cause if read
   * carelessly.
   */
  maxMinutes?: number;
}

/**
 * Nutrition targets (BL-0038).
 *
 * A goal is a *constraint*, never a feature. "150 g of protein a day",
 * "keep cholesterol under 200 mg", "stay under 2,000 calories" and "low
 * carb" differ only in their field values, so one row shape and one
 * evaluator serve all of them — and serve goals nobody has asked for yet.
 * There is deliberately no `lowCarbMode` boolean anywhere in the system.
 */
export type NutritionTargetOperator = "<=" | ">=" | "==";

/**
 * The window a target is measured over. `meal` is a single serving of a
 * single recipe, which is what makes a "fits your goals" badge on a recipe
 * possible without inventing a second concept.
 */
export type NutritionTargetPeriod = "day" | "week" | "meal";

/**
 * One nutrition goal as the recommender sees it (BL-0040) — the stored `nutritionTargets` row
 * minus `active`, because only active goals are ever sent.
 */
export interface RecommendationNutritionTarget {
  nutrientId: string;
  operator: NutritionTargetOperator;
  value: number;
  period: NutritionTargetPeriod;
  label?: string;
  hard?: boolean;
}

/**
 * What the week's plan ALREADY commits, so a `week` target is scored on the gap that remains
 * rather than on the whole goal.
 */
export interface RecommendationPlanNutrition {
  /** nutrientId -> amount, in the estimate's units. */
  nutrients: Record<string, number>;
  coverage: NutritionCoverage;
}

/**
 * Recent event counts for ONE recipe. Counts, not events: the ranker has no
 * business knowing when something happened or in what order, which is what
 * keeps it stateless.
 */
export interface RecommendationInteraction {
  shown: number;
  accepted: number;
  dismissed: number;
  cooked: number;
}

/**
 * Everything the ranker knows about the caller for one request. The ranker is stateless by
 * construction: it holds no user state, so all of it arrives here.
 */
export interface RecommendationRequest {
  pantry: PantryContextItem[];
  preferences: RecommendationPreferences;
  /**
   * canonicalItem → [-1, 1], DERIVED by Convex from its interaction log
   * at request time and never stored as a score (BL-0005 increment 2).
   *
   * Omitted or empty means "no signal", which makes the ranker's
   * `affinity` feature UNAVAILABLE rather than scoring every candidate
   * zero. That distinction is the whole cold-start guarantee: a user who
   * has done nothing has told us nothing, and nothing must not be read as
   * dislike.
   */
  affinities?: Record<string, number>;
  /**
   * Recipes the user already has a copy of. The discover surface REMOVES them; the pantry
   * surface ignores the field.
   */
  savedRecipeIds?: string[];
  /**
   * Recent per-recipe interaction counts, keyed by recipe id. Read only
   * by the discover surface.
   *
   * An OMITTED field and an EMPTY object are different: omitted means no
   * history was sent, so `novelty` is unavailable; empty means this user
   * has interacted with nothing, which makes every candidate equally new.
   */
  interactions?: Record<string, RecommendationInteraction>;
  excludeRecipeIds?: string[];
  limit?: number;
  /**
   * Keep candidates that share nothing with the pantry (BL-0033). The "cook what you have"
   * surface drops them as noise; set selection needs them, because a dish can earn its place by
   * sharing ingredients with the other dinners.
   */
  includeUnmatched?: boolean;
  /**
   * The caller's clock, epoch ms. Sent rather than read from the server clock so scoring stays
   * a pure function of its input. Omitting it makes expiry unavailable — absent data degrades
   * to "no signal", never to a guess.
   */
  now?: number;
  /** ACTIVE goals only: a paused goal is not a goal. */
  nutritionTargets?: RecommendationNutritionTarget[];
  planNutrition?: RecommendationPlanNutrition | null;
}

/** An ingredient the recipe needs that the user does not have. */
export interface RecommendationMissingItem {
  canonicalItem: string;
  display: string;
  /**
   * A keep-on-hand ingredient — salt, oil, the spice rack (BL-0031).
   *
   * It lets a card say "you have everything but the salt" instead of
   * listing salt beside chicken as though they were the same errand.
   * False for anything the dictionary does not recognize, which is the
   * conservative reading.
   */
  staple: boolean;
}

/**
 * A HARD constraint this candidate could not be checked against.
 *
 * It carries the nutrient id rather than a rendered string because only the
 * client has the nutrient catalog to name it with. Its existence is the
 * reason an unmeasured recipe can survive a filter without being presented
 * as having passed it.
 */
export interface RecommendationUnverifiedConstraint {
  nutrientId: string;
  label?: string;
}

/**
 * The most-urgent expiring ingredient a recipe would clear (BL-0050).
 *
 * Typed rather than folded into `reasons` so the card can render "use this
 * soon" distinctly from "you'd like this" — they are different kinds of
 * claim, and telling them apart by prefix-matching a reason string would be
 * brittle.
 */
export interface RecommendationUrgency {
  canonicalItem: string;
  display: string;
  /** Epoch ms, so the card formats it with the same helper as its items strip. */
  useBy: number;
}

/**
 * One ranked recommendation, carrying the reasons that produced it so the UI can explain itself
 * without knowing anything about scoring.
 */
export interface Recommendation {
  recipeId: string;
  title: string;
  /**
   * Where the candidate came from. "generated" is an idea a model
   * invented for this request (BL-0034) — NOT a curated, tested recipe,
   * and the UI must say so. It carries a synthetic `gen-` recipeId that
   * names no stored row until the user accepts it; its full draft rides
   * in `RecommendationResponse.generated`.
   */
  source: "catalog" | "user" | "generated";
  score: number;
  reasons: string[];
  have: string[];
  missing: RecommendationMissingItem[];
  /** Absent when nothing this recipe uses is expiring within the horizon. */
  urgency?: RecommendationUrgency;
  /**
   * 0..1 for how well this candidate closes the plan's remaining gap, or null when nothing
   * could be measured. Null rather than 0: a data gap is not a bad score, and the two must
   * never look alike.
   */
  nutritionFit: number | null;
  nutritionUnverified: RecommendationUnverifiedConstraint[];
}

/**
 * A recipe a model invented for one request (BL-0034).
 *
 * It is a DRAFT: no row exists for it, and its `recipeId` is a synthetic
 * `gen-` id that resolves to nothing. It rides back with the ranked results
 * purely so that accepting a suggestion can persist exactly what the user
 * was shown, instead of asking the model again and getting something
 * slightly different.
 *
 * Only drafts whose candidate SURVIVED ranking appear here. One the
 * avoid-list filter removed is absent from `results` and absent from this
 * list too — a draft the user could save is as dangerous as a result they
 * could see.
 */
export interface GeneratedRecipeDraft {
  /** Joins to the `Recommendation` with the same id. */
  recipeId: string;
  title: string;
  /** Absent when the model gave no usable yield — unknown, never zero. */
  servings?: number;
  ingredients: Ingredient[];
  steps: string[];
}

export interface RecommendationResponse {
  results: Recommendation[];
  /**
   * The full text of every generated candidate in `results`. Always present and always an array
   * — empty whenever generation is unconfigured, ungated or unproductive, which is the common
   * case.
   */
  generated: GeneratedRecipeDraft[];
}

/**
 * `POST /recommendations/discover` — the sibling of the pantry surface.
 *
 * No `generated` sidecar, and that is a decision rather than an omission:
 * an invented recipe is the opposite of a discovery. This surface exists to
 * surface recipes that already exist and that somebody has actually cooked.
 */
export interface DiscoverResponse {
  results: Recommendation[];
}

/** One piece of lead-time work for one meal on one date. */
export interface PrepTask {
  /**
   * Stable across re-derivation: `ruleId:subject`. Check-off is keyed on it, so editing a
   * rule's text preserves the tick and changing a rule's id deliberately does not.
   */
  key: string;
  ruleId: string;
  /** The canonical ingredient, cooking method, or equipment slug the rule matched. */
  subject: string;
  window: PrepWindow;
  text: string;
  source: PrepSource;
  /** ISO date the task is due: the cook date minus the window's lead time. */
  dueOn: string;
  /**
   * The due date has already passed. A missed task is still returned — the whole point of lead
   * time is that forgetting it is the failure worth reporting, not something to hide.
   */
  missed?: boolean;
}

/** Derived prep for one planned meal. */
export interface PrepMeal {
  recipeId: string;
  title: string;
  /** ISO date the meal is planned for. */
  cookDate: string;
  tasks: PrepTask[];
}

export interface PrepTasksResponse {
  /** Revision of the rule table that produced these tasks, for traceability. */
  rulesVersion: string;
  meals: PrepMeal[];
}

export interface PrepTasksRequestMeal {
  recipeId: string;
  cookDate: string;
}

export interface PrepTasksRequest {
  meals: PrepTasksRequestMeal[];
  /**
   * The caller's local date. Supplied rather than read from the server clock: a prep schedule
   * that slips a day is worse than no prep schedule. Omit to leave `missed` unset.
   */
  today?: string;
}
